# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_num_etudiant = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_etudiant.setGeometry(QtCore.QRect(100, 90, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEdit_num_etudiant.setFont(font)
        self.lineEdit_num_etudiant.setText("")
        self.lineEdit_num_etudiant.setObjectName("lineEdit_num_etudiant")
        self.label_num_etudiant = QtWidgets.QLabel(self.centralwidget)
        self.label_num_etudiant.setGeometry(QtCore.QRect(100, 40, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_num_etudiant.setFont(font)
        self.label_num_etudiant.setObjectName("label_num_etudiant")
        self.label_nom_etudiant = QtWidgets.QLabel(self.centralwidget)
        self.label_nom_etudiant.setGeometry(QtCore.QRect(100, 160, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label_nom_etudiant.setFont(font)
        self.label_nom_etudiant.setObjectName("label_nom_etudiant")
        self.lineEdit_nom_etudiant = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nom_etudiant.setGeometry(QtCore.QRect(100, 210, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEdit_nom_etudiant.setFont(font)
        self.lineEdit_nom_etudiant.setText("")
        self.lineEdit_nom_etudiant.setObjectName("lineEdit_nom_etudiant")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 300, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(100, 380, 261, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.label_erreure = QtWidgets.QLabel(self.centralwidget)
        self.label_erreure.setGeometry(QtCore.QRect(420, 90, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_erreure.setFont(font)
        self.label_erreure.setText("")
        self.label_erreure.setObjectName("label_erreure")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_num_etudiant.setText(_translate("MainWindow", "Numéro d\'étudiant"))
        self.label_nom_etudiant.setText(_translate("MainWindow", "Nom de  l\'étudiant"))
        self.pushButton.setText(_translate("MainWindow", "Valider"))
